package com.viptrip.common.entity;

// Generated 2017-11-7 18:29:51 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TTmcApproveRecordId generated by hbm2java
 */
@Embeddable
public class TTmcApproveRecordId implements java.io.Serializable {

	private int approveLevel;
	private long approveProcessId;
	private int flowid;

	public TTmcApproveRecordId() {
	}

	public TTmcApproveRecordId(int approveLevel, long approveProcessId,
			int flowid) {
		this.approveLevel = approveLevel;
		this.approveProcessId = approveProcessId;
		this.flowid = flowid;
	}

	@Column(name = "APPROVE_LEVEL", nullable = false, precision = 5, scale = 0)
	public int getApproveLevel() {
		return this.approveLevel;
	}

	public void setApproveLevel(int approveLevel) {
		this.approveLevel = approveLevel;
	}

	@Column(name = "APPROVE_PROCESS_ID", nullable = false, precision = 12, scale = 0)
	public long getApproveProcessId() {
		return this.approveProcessId;
	}

	public void setApproveProcessId(long approveProcessId) {
		this.approveProcessId = approveProcessId;
	}

	@Column(name = "FLOWID", nullable = false, precision = 5, scale = 0)
	public int getFlowid() {
		return this.flowid;
	}

	public void setFlowid(int flowid) {
		this.flowid = flowid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TTmcApproveRecordId))
			return false;
		TTmcApproveRecordId castOther = (TTmcApproveRecordId) other;

		return (this.getApproveLevel() == castOther.getApproveLevel())
				&& (this.getApproveProcessId() == castOther
						.getApproveProcessId())
				&& (this.getFlowid() == castOther.getFlowid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getApproveLevel();
		result = 37 * result + (int) this.getApproveProcessId();
		result = 37 * result + this.getFlowid();
		return result;
	}

}
