package com.viptrip.common.entity;

// Generated 2017-11-7 18:29:51 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TTmcApproveFlowId generated by hbm2java
 */
@Embeddable
public class TTmcApproveFlowId implements java.io.Serializable {

	private int approveLevel;
	private long approvePolicyId;
	private int flowid;

	public TTmcApproveFlowId() {
	}

	public TTmcApproveFlowId(int approveLevel, long approvePolicyId, int flowid) {
		this.approveLevel = approveLevel;
		this.approvePolicyId = approvePolicyId;
		this.flowid = flowid;
	}

	@Column(name = "APPROVE_LEVEL", nullable = false, precision = 5, scale = 0)
	public int getApproveLevel() {
		return this.approveLevel;
	}

	public void setApproveLevel(int approveLevel) {
		this.approveLevel = approveLevel;
	}

	@Column(name = "APPROVE_POLICY_ID", nullable = false, precision = 12, scale = 0)
	public long getApprovePolicyId() {
		return this.approvePolicyId;
	}

	public void setApprovePolicyId(long approvePolicyId) {
		this.approvePolicyId = approvePolicyId;
	}

	@Column(name = "FLOWID", nullable = false, precision = 5, scale = 0)
	public int getFlowid() {
		return this.flowid;
	}

	public void setFlowid(int flowid) {
		this.flowid = flowid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TTmcApproveFlowId))
			return false;
		TTmcApproveFlowId castOther = (TTmcApproveFlowId) other;

		return (this.getApproveLevel() == castOther.getApproveLevel())
				&& (this.getApprovePolicyId() == castOther.getApprovePolicyId())
				&& (this.getFlowid() == castOther.getFlowid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getApproveLevel();
		result = 37 * result + (int) this.getApprovePolicyId();
		result = 37 * result + this.getFlowid();
		return result;
	}

}
