package com.viptrip.common.entity;

// Generated 2017-11-7 18:29:51 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TTmcApproveProcess generated by hbm2java
 */
@Entity
@Table(name = "T_TMC_APPROVE_PROCESS")
public class TTmcApproveProcess implements java.io.Serializable {

	private long approveProcessId;
	private Long approvePolicyId;
	private Integer businessType;
	private Integer orderid;
	private String orderno;
	private Long enterpId;
	private String enterpName;
	private Integer travelType;
	private Integer payType;
	private String productName;
	private String productDetail;
	private String extend;
	private BigDecimal aomunt;
	private Date bookTime;
	private Long bookerId;
	private String bookerName;
	private String bookerMobile;
	private String bookerEmail;
	private String state;
	private Integer processLevel;
	private Integer processState;

	public TTmcApproveProcess() {
	}

	public TTmcApproveProcess(long approveProcessId) {
		this.approveProcessId = approveProcessId;
	}

	public TTmcApproveProcess(long approveProcessId, Long approvePolicyId,
			Integer businessType, Integer orderid, String orderno,
			Long enterpId, String enterpName, Integer travelType,
			Integer payType, String productName, String productDetail,
			String extend, BigDecimal aomunt, Date bookTime, Long bookerId,
			String bookerName, String bookerMobile, String bookerEmail,
			String state, Integer processLevel, Integer processState) {
		this.approveProcessId = approveProcessId;
		this.approvePolicyId = approvePolicyId;
		this.businessType = businessType;
		this.orderid = orderid;
		this.orderno = orderno;
		this.enterpId = enterpId;
		this.enterpName = enterpName;
		this.travelType = travelType;
		this.payType = payType;
		this.productName = productName;
		this.productDetail = productDetail;
		this.extend = extend;
		this.aomunt = aomunt;
		this.bookTime = bookTime;
		this.bookerId = bookerId;
		this.bookerName = bookerName;
		this.bookerMobile = bookerMobile;
		this.bookerEmail = bookerEmail;
		this.state = state;
		this.processLevel = processLevel;
		this.processState = processState;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="SEQ_T_TMC_APPROVE_PROCESS")
	@SequenceGenerator(name="SEQ_T_TMC_APPROVE_PROCESS",allocationSize=1,initialValue=1, sequenceName="SEQ_T_TMC_APPROVE_PROCESS")
	@Column(name = "APPROVE_PROCESS_ID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getApproveProcessId() {
		return this.approveProcessId;
	}

	public void setApproveProcessId(long approveProcessId) {
		this.approveProcessId = approveProcessId;
	}

	@Column(name = "APPROVE_POLICY_ID", precision = 12, scale = 0)
	public Long getApprovePolicyId() {
		return this.approvePolicyId;
	}

	public void setApprovePolicyId(Long approvePolicyId) {
		this.approvePolicyId = approvePolicyId;
	}

	@Column(name = "BUSINESS_TYPE", precision = 5, scale = 0)
	public Integer getBusinessType() {
		return this.businessType;
	}

	public void setBusinessType(Integer businessType) {
		this.businessType = businessType;
	}

	@Column(name = "ORDERID", precision = 5, scale = 0)
	public Integer getOrderid() {
		return this.orderid;
	}

	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	@Column(name = "ORDERNO", length = 200)
	public String getOrderno() {
		return this.orderno;
	}

	public void setOrderno(String orderno) {
		this.orderno = orderno;
	}

	@Column(name = "ENTERP_ID", precision = 12, scale = 0)
	public Long getEnterpId() {
		return this.enterpId;
	}

	public void setEnterpId(Long enterpId) {
		this.enterpId = enterpId;
	}

	@Column(name = "ENTERP_NAME", length = 512)
	public String getEnterpName() {
		return this.enterpName;
	}

	public void setEnterpName(String enterpName) {
		this.enterpName = enterpName;
	}

	@Column(name = "TRAVEL_TYPE", precision = 5, scale = 0)
	public Integer getTravelType() {
		return this.travelType;
	}

	public void setTravelType(Integer travelType) {
		this.travelType = travelType;
	}

	@Column(name = "PAY_TYPE", precision = 5, scale = 0)
	public Integer getPayType() {
		return this.payType;
	}

	public void setPayType(Integer payType) {
		this.payType = payType;
	}

	@Column(name = "PRODUCT_NAME", length = 200)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "PRODUCT_DETAIL", length = 200)
	public String getProductDetail() {
		return this.productDetail;
	}

	public void setProductDetail(String productDetail) {
		this.productDetail = productDetail;
	}

	@Column(name = "EXTEND", length = 4000)
	public String getExtend() {
		return this.extend;
	}

	public void setExtend(String extend) {
		this.extend = extend;
	}

	@Column(name = "AOMUNT", precision = 10)
	public BigDecimal getAomunt() {
		return this.aomunt;
	}

	public void setAomunt(BigDecimal aomunt) {
		this.aomunt = aomunt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "BOOK_TIME", length = 7)
	public Date getBookTime() {
		return this.bookTime;
	}

	public void setBookTime(Date bookTime) {
		this.bookTime = bookTime;
	}

	@Column(name = "BOOKER_ID", precision = 12, scale = 0)
	public Long getBookerId() {
		return this.bookerId;
	}

	public void setBookerId(Long bookerId) {
		this.bookerId = bookerId;
	}

	@Column(name = "BOOKER_NAME", length = 32)
	public String getBookerName() {
		return this.bookerName;
	}

	public void setBookerName(String bookerName) {
		this.bookerName = bookerName;
	}

	@Column(name = "BOOKER_MOBILE", length = 20)
	public String getBookerMobile() {
		return this.bookerMobile;
	}

	public void setBookerMobile(String bookerMobile) {
		this.bookerMobile = bookerMobile;
	}

	@Column(name = "BOOKER_EMAIL", length = 200)
	public String getBookerEmail() {
		return this.bookerEmail;
	}

	public void setBookerEmail(String bookerEmail) {
		this.bookerEmail = bookerEmail;
	}

	@Column(name = "STATE", precision = 5, scale = 0)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "PROCESS_LEVEL", precision = 5, scale = 0)
	public Integer getProcessLevel() {
		return this.processLevel;
	}

	public void setProcessLevel(Integer processLevel) {
		this.processLevel = processLevel;
	}

	@Column(name = "PROCESS_STATE", precision = 5, scale = 0)
	public Integer getProcessState() {
		return this.processState;
	}

	public void setProcessState(Integer processState) {
		this.processState = processState;
	}

}
