package com.viptrip.common.entity;

// Generated 2017-11-7 18:29:51 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TTmcApproveTravellerId generated by hbm2java
 */
@Embeddable
public class TTmcApproveTravellerId implements java.io.Serializable {

	private int flowid;
	private long approveProcessId;

	public TTmcApproveTravellerId() {
	}

	public TTmcApproveTravellerId(int flowid, long approveProcessId) {
		this.flowid = flowid;
		this.approveProcessId = approveProcessId;
	}

	@Column(name = "FLOWID", nullable = false, precision = 5, scale = 0)
	public int getFlowid() {
		return this.flowid;
	}

	public void setFlowid(int flowid) {
		this.flowid = flowid;
	}

	@Column(name = "APPROVE_PROCESS_ID", nullable = false, precision = 12, scale = 0)
	public long getApproveProcessId() {
		return this.approveProcessId;
	}

	public void setApproveProcessId(long approveProcessId) {
		this.approveProcessId = approveProcessId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TTmcApproveTravellerId))
			return false;
		TTmcApproveTravellerId castOther = (TTmcApproveTravellerId) other;

		return (this.getFlowid() == castOther.getFlowid())
				&& (this.getApproveProcessId() == castOther
						.getApproveProcessId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getFlowid();
		result = 37 * result + (int) this.getApproveProcessId();
		return result;
	}

}
