package com.viptrip.common.entity;

// Generated 2017-11-7 18:29:51 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TTmcApproveProcessLable generated by hbm2java
 */
@Entity
@Table(name = "T_TMC_APPROVE_PROCESS_LABLE")
public class TTmcApproveProcessLable implements java.io.Serializable {

	private TTmcApproveProcessLableId id;

	public TTmcApproveProcessLable() {
	}

	public TTmcApproveProcessLable(TTmcApproveProcessLableId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "lableType", column = @Column(name = "LABLE_TYPE", nullable = false, precision = 5, scale = 0)),
			@AttributeOverride(name = "approveProcessId", column = @Column(name = "APPROVE_PROCESS_ID", nullable = false, precision = 12, scale = 0)),
			@AttributeOverride(name = "lableValue", column = @Column(name = "LABLE_VALUE", nullable = false, precision = 5, scale = 0)) })
	public TTmcApproveProcessLableId getId() {
		return this.id;
	}

	public void setId(TTmcApproveProcessLableId id) {
		this.id = id;
	}

}
