package com.viptrip.common.entity;

// Generated 2017-11-7 18:29:51 by Hibernate Tools 4.3.1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TTmcApproveTraveller generated by hbm2java
 */
@Entity
@Table(name = "T_TMC_APPROVE_TRAVELLER")
public class TTmcApproveTraveller implements java.io.Serializable {

	private TTmcApproveTravellerId id;
	private Long travellerId;
	private String travellerName;
	private String travellerMobile;
	private String travellerEmail;
	private Long orgId;
	private String orgName;
	private Long costId;
	private String costName;

	public TTmcApproveTraveller() {
	}

	public TTmcApproveTraveller(TTmcApproveTravellerId id) {
		this.id = id;
	}

	public TTmcApproveTraveller(TTmcApproveTravellerId id, Long travellerId,
			String travellerName, String travellerMobile,
			String travellerEmail, Long orgId, String orgName, Long costId,
			String costName) {
		this.id = id;
		this.travellerId = travellerId;
		this.travellerName = travellerName;
		this.travellerMobile = travellerMobile;
		this.travellerEmail = travellerEmail;
		this.orgId = orgId;
		this.orgName = orgName;
		this.costId = costId;
		this.costName = costName;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "flowid", column = @Column(name = "FLOWID", nullable = false, precision = 5, scale = 0)),
			@AttributeOverride(name = "approveProcessId", column = @Column(name = "APPROVE_PROCESS_ID", nullable = false, precision = 12, scale = 0)) })
	public TTmcApproveTravellerId getId() {
		return this.id;
	}

	public void setId(TTmcApproveTravellerId id) {
		this.id = id;
	}

	@Column(name = "TRAVELLER_ID", precision = 12, scale = 0)
	public Long getTravellerId() {
		return this.travellerId;
	}

	public void setTravellerId(Long travellerId) {
		this.travellerId = travellerId;
	}

	@Column(name = "TRAVELLER_NAME", length = 32)
	public String getTravellerName() {
		return this.travellerName;
	}

	public void setTravellerName(String travellerName) {
		this.travellerName = travellerName;
	}

	@Column(name = "TRAVELLER_MOBILE", length = 20)
	public String getTravellerMobile() {
		return this.travellerMobile;
	}

	public void setTravellerMobile(String travellerMobile) {
		this.travellerMobile = travellerMobile;
	}

	@Column(name = "TRAVELLER_EMAIL", length = 200)
	public String getTravellerEmail() {
		return this.travellerEmail;
	}

	public void setTravellerEmail(String travellerEmail) {
		this.travellerEmail = travellerEmail;
	}

	@Column(name = "ORG_ID", precision = 12, scale = 0)
	public Long getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	@Column(name = "ORG_NAME", length = 512)
	public String getOrgName() {
		return this.orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}

	@Column(name = "COST_ID", precision = 12, scale = 0)
	public Long getCostId() {
		return this.costId;
	}

	public void setCostId(Long costId) {
		this.costId = costId;
	}

	@Column(name = "COST_NAME", length = 512)
	public String getCostName() {
		return this.costName;
	}

	public void setCostName(String costName) {
		this.costName = costName;
	}

}
