
package com.viptrip.wetrip.wsclient;
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-11-19T19:55:15.640+08:00
 * Generated source version: 2.7.6
 * 本文件夹下第 8个文件，和学银 检查完成 时间：2015年6月12日09:50:34
 */
public final class CreateIBEToAndFroPNR_CreateIBEToAndFroPNRImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.viptrip.com/", "CreateIBEToAndFroPNRImplService");

    private CreateIBEToAndFroPNR_CreateIBEToAndFroPNRImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CreateIBEToAndFroPNRImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CreateIBEToAndFroPNRImplService ss = new CreateIBEToAndFroPNRImplService(wsdlURL, SERVICE_NAME);
        CreateIBEToAndFroPNR port = ss.getCreateIBEToAndFroPNRImplPort();  
        
        {
        //system.out.println("Invoking createManyPNR...");
        java.util.List<java.lang.String> _createManyPNR_arg0 = null;
        java.util.List<java.lang.String> _createManyPNR_arg1 = null;
        java.util.List<java.lang.Integer> _createManyPNR_arg2 = null;
        java.util.List<java.lang.String> _createManyPNR_arg3 = null;
        java.util.List<java.lang.String> _createManyPNR_arg4 = null;
        java.util.List<java.lang.String> _createManyPNR_arg5 = null;
        java.util.List<java.lang.String> _createManyPNR_arg6 = null;
        java.util.List<java.lang.String> _createManyPNR_arg7 = null;
        java.util.List<java.lang.String> _createManyPNR_arg8 = null;
        PnrResult _createManyPNR__return = port.createManyPNR(_createManyPNR_arg0, _createManyPNR_arg1, _createManyPNR_arg2, _createManyPNR_arg3, _createManyPNR_arg4, _createManyPNR_arg5, _createManyPNR_arg6, _createManyPNR_arg7, _createManyPNR_arg8);
        //system.out.println("createManyPNR.result=" + _createManyPNR__return);


        }

        System.exit(0);
    }

}
