package com.viptrip.wetrip.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-30T15:32:15.333+08:00
 * Generated source version: 2.7.6
 */
@WebService(targetNamespace = "http://webservice.viptrip.com/", name = "CreateIBEPNR")
@XmlSeeAlso({ObjectFactory.class})
public interface CreateIBEPNR {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "CreatePNR", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.CreatePNR")
    @WebMethod(operationName = "CreatePNR")
    @ResponseWrapper(localName = "CreatePNRResponse", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.CreatePNRResponse")
    public PnrResult createPNR(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.lang.String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.lang.String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.util.List<java.lang.String> arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.util.List<java.lang.String> arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.util.List<java.lang.String> arg8
    );
}
