package com.viptrip.wetrip.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-11-19T19:55:15.788+08:00
 * Generated source version: 2.7.6
 * 本文件夹下第 9个文件，和学银 检查完成 时间：2015年6月12日09:50:49
 */
@WebService(targetNamespace = "http://webservice.viptrip.com/", name = "CreateIBEToAndFroPNR")
@XmlSeeAlso({ObjectFactory.class})
public interface CreateIBEToAndFroPNR {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "CreateManyPNR", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.CreateManyPNR")
    @WebMethod(operationName = "CreateManyPNR")
    @ResponseWrapper(localName = "CreateManyPNRResponse", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.CreateManyPNRResponse")
    public PnrResult createManyPNR(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<java.lang.String> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.util.List<java.lang.String> arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.util.List<java.lang.Integer> arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.util.List<java.lang.String> arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        java.util.List<java.lang.String> arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        java.util.List<java.lang.String> arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        java.util.List<java.lang.String> arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        java.util.List<java.lang.String> arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        java.util.List<java.lang.String> arg8
    );
}
