
package com.viptrip.wetrip.wsclient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-09-30T15:32:15.196+08:00
 * Generated source version: 2.7.6
 * 本文件夹下第5个文件，和学银 检查完成 时间：2015年6月12日09:49:18
 */
public final class CreateIBEPNR_CreateIBEPNRImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.viptrip.com/", "CreateIBEPNRImplService");

    private CreateIBEPNR_CreateIBEPNRImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CreateIBEPNRImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CreateIBEPNRImplService ss = new CreateIBEPNRImplService(wsdlURL, SERVICE_NAME);
        CreateIBEPNR port = ss.getCreateIBEPNRImplPort();  
        
        {
        //system.out.println("Invoking createPNR...");
        java.util.List<java.lang.String> _createPNR_arg0 = null;
        java.lang.String _createPNR_arg1 = "";
        int _createPNR_arg2 = 0;
        java.lang.String _createPNR_arg3 = "";
        java.lang.String _createPNR_arg4 = "";
        java.lang.String _createPNR_arg5 = "";
        java.util.List<java.lang.String> _createPNR_arg6 = null;
        java.util.List<java.lang.String> _createPNR_arg7 = null;
        java.util.List<java.lang.String> _createPNR_arg8 = null;
        PnrResult _createPNR__return = port.createPNR(_createPNR_arg0, _createPNR_arg1, _createPNR_arg2, _createPNR_arg3, _createPNR_arg4, _createPNR_arg5, _createPNR_arg6, _createPNR_arg7, _createPNR_arg8);
        //system.out.println("createPNR.result=" + _createPNR__return);


        }

        System.exit(0);
    }

}
