
package com.viptrip.wetrip.wsclient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-10-10T13:04:59.357+08:00
 * Generated source version: 2.7.6
 * 本文件夹下第15 个文件，和学银 检查完成 时间：2015年6月12日09:53:41
 */
public final class DeleteIBEPNRImplDelegate_DeleteIBEPNRImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.viptrip.com/", "DeleteIBEPNRImplService");

    private DeleteIBEPNRImplDelegate_DeleteIBEPNRImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = DeleteIBEPNRImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DeleteIBEPNRImplService ss = new DeleteIBEPNRImplService(wsdlURL, SERVICE_NAME);
        DeleteIBEPNRImplDelegate port = ss.getDeleteIBEPNRImplPort();  
        
        {
        //system.out.println("Invoking deletePNR...");
        java.lang.String _deletePNR_arg0 = "";
        java.lang.String _deletePNR__return = port.deletePNR(_deletePNR_arg0);
        //system.out.println("deletePNR.result=" + _deletePNR__return);


        }

        System.exit(0);
    }

}
