package com.viptrip.wetrip.wsclient;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.viptrip.resource.Const;
import com.viptrip.util.PropertiesUtils;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-10-10T13:04:59.494+08:00
 * Generated source version: 2.7.6
 * 本文件夹下第 17个文件，和学银 检查完成 时间：2015年6月12日09:54:23
 */
@WebServiceClient(name = "DeleteIBEPNRImplService", 
                  wsdlLocation = "/new_ws/DeleteIBEPNRImplPort?wsdl",
                  targetNamespace = "http://webservice.viptrip.com/") 
public class DeleteIBEPNRImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.viptrip.com/", "DeleteIBEPNRImplService");
    public final static QName DeleteIBEPNRImplPort = new QName("http://webservice.viptrip.com/", "DeleteIBEPNRImplPort");
    static {
        URL url = null;
		StringBuffer partURL=new StringBuffer();
		try {
			partURL.append(PropertiesUtils.getProperty(Const.PRO_IBESERVER_IP,Const.FILE_IBESERVER));
			partURL.append(PropertiesUtils.getProperty(Const.PRO_IBESERVER_PORT,Const.FILE_IBESERVER));
		} catch (IOException e) {
			e.printStackTrace();
		}
        try {
            url = new URL("http://" + partURL + 
            		"/new_ws/DeleteIBEPNRImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DeleteIBEPNRImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://" + partURL + 
            		"/new_ws/DeleteIBEPNRImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DeleteIBEPNRImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeleteIBEPNRImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeleteIBEPNRImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DeleteIBEPNRImplDelegate
     */
    @WebEndpoint(name = "DeleteIBEPNRImplPort")
    public DeleteIBEPNRImplDelegate getDeleteIBEPNRImplPort() {
        return super.getPort(DeleteIBEPNRImplPort, DeleteIBEPNRImplDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeleteIBEPNRImplDelegate
     */
    /*
    @WebEndpoint(name = "DeleteIBEPNRImplPort")
    public DeleteIBEPNRImplDelegate getDeleteIBEPNRImplPort(WebServiceFeature... features) {
        return super.getPort(DeleteIBEPNRImplPort, DeleteIBEPNRImplDelegate.class, features);
    }
*/
}
