
package com.viptrip.wetrip.wsclient;
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-11-20T16:34:07.995+08:00
 * Generated source version: 2.7.6
 * 本文件夹下第 22个文件，和学银 检查完成 时间：2015年6月12日09:55:27
 */
public final class GetIBEBigplaitImplDelegate_GetIBEBigplaitImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.viptrip.com/", "GetIBEBigplaitImplService");

    private GetIBEBigplaitImplDelegate_GetIBEBigplaitImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GetIBEBigplaitImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GetIBEBigplaitImplService ss = new GetIBEBigplaitImplService(wsdlURL, SERVICE_NAME);
        GetIBEBigplaitImplDelegate port = ss.getGetIBEBigplaitImplPort();  
        
        {
        //system.out.println("Invoking getIBEBigplait...");
        java.lang.String _getIBEBigplait_arg0 = "";
        java.util.List<java.lang.String> _getIBEBigplait__return = port.getIBEBigplait(_getIBEBigplait_arg0);
        //system.out.println("getIBEBigplait.result=" + _getIBEBigplait__return);


        }

        System.exit(0);
    }

}
