package com.viptrip.wetrip.wsclient;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.viptrip.resource.Const;
import com.viptrip.util.PropertiesUtils;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-11-20T16:34:08.139+08:00
 * Generated source version: 2.7.6
 * 本文件夹下第 24个文件，和学银 检查完成 时间：2015年6月12日09:55:27
 */
@WebServiceClient(name = "GetIBEBigplaitImplService", 
                  wsdlLocation = "/new_ws/GetIBEBigplaitImplPort?wsdl",
                  targetNamespace = "http://webservice.viptrip.com/") 
public class GetIBEBigplaitImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.viptrip.com/", "GetIBEBigplaitImplService");
    public final static QName GetIBEBigplaitImplPort = new QName("http://webservice.viptrip.com/", "GetIBEBigplaitImplPort");
    static {
        URL url = null;
		StringBuffer partURL=new StringBuffer();
		try {
			partURL.append(PropertiesUtils.getProperty(Const.PRO_IBESERVER_IP,Const.FILE_IBESERVER));
			partURL.append(PropertiesUtils.getProperty(Const.PRO_IBESERVER_PORT,Const.FILE_IBESERVER));
		} catch (IOException e) {
			e.printStackTrace();
		}
        try {
            url = new URL("http://" + partURL + 
            		"/new_ws/GetIBEBigplaitImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetIBEBigplaitImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://" + partURL + 
            		"/new_ws/GetIBEBigplaitImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetIBEBigplaitImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetIBEBigplaitImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetIBEBigplaitImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GetIBEBigplaitImplDelegate
     */
    @WebEndpoint(name = "GetIBEBigplaitImplPort")
    public GetIBEBigplaitImplDelegate getGetIBEBigplaitImplPort() {
        return super.getPort(GetIBEBigplaitImplPort, GetIBEBigplaitImplDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetIBEBigplaitImplDelegate
     
    @WebEndpoint(name = "GetIBEBigplaitImplPort")
    public GetIBEBigplaitImplDelegate getGetIBEBigplaitImplPort(WebServiceFeature... features) {
        return super.getPort(GetIBEBigplaitImplPort, GetIBEBigplaitImplDelegate.class, features);
    }
*/
}
