package com.viptrip.wetrip.wsclient;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.viptrip.resource.Const;
import com.viptrip.util.PropertiesUtils;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-12-19T16:33:35.834+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "GetIBEPNRFlightImplService", 
                  wsdlLocation = "/new_ws/GetIBEPNRFlightImplPort?wsdl",
                  targetNamespace = "http://webservice.viptrip.com/") 
public class GetIBEPNRFlightImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.viptrip.com/", "GetIBEPNRFlightImplService");
    public final static QName GetIBEPNRFlightImplPort = new QName("http://webservice.viptrip.com/", "GetIBEPNRFlightImplPort");
    static {
        URL url = null;  
        StringBuffer partURL=new StringBuffer();
		try {
			partURL.append(PropertiesUtils.getProperty(Const.PRO_IBESERVER_IP,Const.FILE_IBESERVER));
			partURL.append(PropertiesUtils.getProperty(Const.PRO_IBESERVER_PORT,Const.FILE_IBESERVER));
		} catch (IOException e) {
			e.printStackTrace();
		}
        try {
            url = new URL("http://" + partURL + "/new_ws/GetIBEPNRFlightImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetIBEPNRFlightImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://" + partURL + 
            		"/new_ws/GetIBEPNRFlightImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetIBEPNRFlightImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetIBEPNRFlightImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetIBEPNRFlightImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GetIBEPNRFlightImplDelegate
     */
    @WebEndpoint(name = "GetIBEPNRFlightImplPort")
    public GetIBEPNRFlightImplDelegate getGetIBEPNRFlightImplPort() {
        return super.getPort(GetIBEPNRFlightImplPort, GetIBEPNRFlightImplDelegate.class);
    }
/*
    
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetIBEPNRFlightImplDelegate
     
    @WebEndpoint(name = "GetIBEPNRFlightImplPort")
    public GetIBEPNRFlightImplDelegate getGetIBEPNRFlightImplPort(WebServiceFeature... features) {
        return super.getPort(GetIBEPNRFlightImplPort, GetIBEPNRFlightImplDelegate.class, features);
    }
*/
}
