package com.viptrip.wetrip.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-11-20T16:34:08.119+08:00
 * Generated source version: 2.7.6
 * 本文件夹下第 23个文件，和学银 检查完成 时间：2015年6月12日09:55:27
 */
@WebService(targetNamespace = "http://webservice.viptrip.com/", name = "GetIBEBigplaitImplDelegate")
@XmlSeeAlso({ObjectFactory.class})
public interface GetIBEBigplaitImplDelegate {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getIBEBigplait", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.GetIBEBigplait")
    @WebMethod
    @ResponseWrapper(localName = "getIBEBigplaitResponse", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.GetIBEBigplaitResponse")
    public java.util.List<java.lang.String> getIBEBigplait(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
    
    /**
     * 
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStopStr", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.GetStopStr")
    @ResponseWrapper(localName = "getStopStrResponse", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.GetStopStrResponse")
    public String getStopStr(
            @WebParam(name = "arg0", targetNamespace = "") 
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "") 
            String arg1
    );
}
