package com.viptrip.wetrip.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-10-11T17:28:35.298+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://webservice.viptrip.com/", name = "GetIBETicketNoImplDelegate")
@XmlSeeAlso({ObjectFactory.class})
public interface GetIBETicketNoImplDelegate {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getTicketNo", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.GetTicketNo")
    @WebMethod
    @ResponseWrapper(localName = "getTicketNoResponse", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.GetTicketNoResponse")
    public java.util.List<java.lang.String> getTicketNo(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
