package com.viptrip.wetrip.wsclient;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.viptrip.resource.Const;
import com.viptrip.util.PropertiesUtils;


/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-10-17T11:04:21.923+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "GetIBEPNRMsgImplService", 
                  wsdlLocation = "/new_ws/GetIBEPNRMsgImplPort?wsdl",
                  targetNamespace = "http://webservice.viptrip.com/") 
public class GetIBEPNRMsgImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.viptrip.com/", "GetIBEPNRMsgImplService");
    public final static QName GetIBEPNRMsgImplPort = new QName("http://webservice.viptrip.com/", "GetIBEPNRMsgImplPort");
    static {
        URL url = null;
		StringBuffer partURL=new StringBuffer();
		try {
			partURL.append(PropertiesUtils.getProperty(Const.PRO_IBESERVER_IP,Const.FILE_IBESERVER));
			partURL.append(PropertiesUtils.getProperty(Const.PRO_IBESERVER_PORT,Const.FILE_IBESERVER));
		} catch (IOException e) {
			e.printStackTrace();
		}
        try {
            url = new URL("http://" + partURL + "/new_ws/GetIBEPNRMsgImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetIBEPNRMsgImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://" + partURL + 
            		"/new_ws/GetIBEPNRMsgImplPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetIBEPNRMsgImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetIBEPNRMsgImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetIBEPNRMsgImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GetIBEPNRMsgImplDelegate
     */
    @WebEndpoint(name = "GetIBEPNRMsgImplPort")
    public GetIBEPNRMsgImplDelegate getGetIBEPNRMsgImplPort() {
        return super.getPort(GetIBEPNRMsgImplPort, GetIBEPNRMsgImplDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetIBEPNRMsgImplDelegate
     */
/*    @WebEndpoint(name = "GetIBEPNRMsgImplPort")
    public GetIBEPNRMsgImplDelegate getGetIBEPNRMsgImplPort(WebServiceFeature... features) {
        return super.getPort(GetIBEPNRMsgImplPort, GetIBEPNRMsgImplDelegate.class, features);
    }
*/
}
