package com.viptrip.wetrip.wsclient;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IBEPNRAddPATAImplDelegate", targetNamespace = "http://webservice.viptrip.com/")
public interface IBEPNRAddPATAImplDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.String>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "pnrAddPata", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.webservice.PnrAddPata")
	@ResponseWrapper(localName = "pnrAddPataResponse", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.webservice.PnrAddPataResponse")
	public List<String> pnrAddPata(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.String>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "autoIssueProcess", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip365.ws.AutoIssueProcess")
	@ResponseWrapper(localName = "autoIssueProcessResponse", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip365.ws.AutoIssueProcessResponse")
	public List<String> autoIssueProcess(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") Double arg2);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<java.lang.String>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "rrAndIssueIBETickeForAuto", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip365.ws.RrAndIssueIBETickeForAuto")
	@ResponseWrapper(localName = "rrAndIssueIBETickeForAutoResponse", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip365.ws.RrAndIssueIBETickeForAutoResponse")
	public List<String> rrAndIssueIBETickeForAuto(
			@WebParam(name = "arg0", targetNamespace = "") List<String> arg0);

	/**
	 * 
	 * @param arg2
	 * @param arg1
	 * @param arg0
	 * @return returns java.util.List<java.lang.String>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "checkPriceOnly", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip365.ws.CheckPriceOnly")
	@ResponseWrapper(localName = "checkPriceOnlyResponse", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip365.ws.CheckPriceOnlyResponse")
	public List<String> checkPriceOnly(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1,
			@WebParam(name = "arg2", targetNamespace = "") Double arg2);

}
