package com.viptrip.wetrip.wsclient;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.viptrip.resource.Const;
import com.viptrip.util.PropertiesUtils;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * IBEPNRAddPATAImplService service = new IBEPNRAddPATAImplService();
 * IBEPNRAddPATAImplDelegate portType = service.getIBEPNRAddPATAImplPort();
 * portType.pnrAddPata(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "IBEPNRAddPATAImplService", targetNamespace = "http://webservice.viptrip.com/", wsdlLocation = "http://10.0.4.152:8089/new_ws/IBEPNRAddPATAImplPort?wsdl")
public class IBEPNRAddPATAImplService extends Service {

	private final static URL IBEPNRADDPATAIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(IBEPNRAddPATAImplService.class
					.getName());

	static {
		URL url = null;
		StringBuffer partURL=new StringBuffer();
		try {
			partURL.append(PropertiesUtils.getProperty(Const.PRO_IBESERVER_IP,Const.FILE_IBESERVER));
			partURL.append(PropertiesUtils.getProperty(Const.PRO_IBESERVER_PORT,Const.FILE_IBESERVER));
		} catch (IOException e) {
			e.printStackTrace();
		}
		try {
            url = new URL("http://" + partURL + "/new_ws/IBEPNRAddPATAImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetIBETicketNoImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://" + partURL + 
            		"/new_ws/IBEPNRAddPATAImplPort?wsdl");
        }
		
		IBEPNRADDPATAIMPLSERVICE_WSDL_LOCATION = url;
	}

	public IBEPNRAddPATAImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public IBEPNRAddPATAImplService() {
		super(IBEPNRADDPATAIMPLSERVICE_WSDL_LOCATION, new QName(
				"http://webservice.viptrip.com/", "IBEPNRAddPATAImplService"));
	}

	/**
	 * 
	 * @return returns IBEPNRAddPATAImplDelegate
	 */
	@WebEndpoint(name = "IBEPNRAddPATAImplPort")
	public IBEPNRAddPATAImplDelegate getIBEPNRAddPATAImplPort() {
		return super.getPort(new QName("http://webservice.viptrip.com/",
				"IBEPNRAddPATAImplPort"), IBEPNRAddPATAImplDelegate.class);
	}

}