package com.viptrip.wetrip.wsclient;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-10-11T12:35:51.985+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://webservice.viptrip.com/", name = "IBEQuitTicketImplDelegate")
@XmlSeeAlso({ObjectFactory.class})
public interface IBEQuitTicketImplDelegate {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "confirmAutomaticRefund", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.ConfirmAutomaticRefund")
    @WebMethod
    @ResponseWrapper(localName = "confirmAutomaticRefundResponse", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.ConfirmAutomaticRefundResponse")
    public java.lang.String confirmAutomaticRefund(
        @WebParam(name = "arg0", targetNamespace = "")
        TrfdResult arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        java.lang.String arg3
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "automaticRefund", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.AutomaticRefund")
    @WebMethod
    @ResponseWrapper(localName = "automaticRefundResponse", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.AutomaticRefundResponse")
    public TrfdResult automaticRefund(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
