package com.viptrip.wetrip.wsclient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-10-10T13:57:26.284+08:00
 * Generated source version: 2.7.6
 * 
 */
public final class IBETicketImplDelegate_IBETicketImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.viptrip.com/", "IBETicketImplService");

    private IBETicketImplDelegate_IBETicketImplPort_Client() {
    }

//    public static void main(String args[]) throws java.lang.Exception {
//        URL wsdlURL = IBETicketImplService.WSDL_LOCATION;
//        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
//            File wsdlFile = new File(args[0]);
//            try {
//                if (wsdlFile.exists()) {
//                    wsdlURL = wsdlFile.toURI().toURL();
//                } else {
//                    wsdlURL = new URL(args[0]);
//                }
//            } catch (MalformedURLException e) {
//                e.printStackTrace();
//            }
//        }
//      
//        IBETicketImplService ss = new IBETicketImplService(wsdlURL, SERVICE_NAME);
//        IBETicketImplDelegate port = ss.getIBETicketImplPort();  
//        
//        {
//        //system.out.println("Invoking sellIBETicket...");
//        java.lang.String _sellIBETicket_arg0 = "";
//        int _sellIBETicket_arg1 = 0;
//        java.lang.String _sellIBETicket__return = port.sellIBETicket(_sellIBETicket_arg0, _sellIBETicket_arg1);
//        //system.out.println("sellIBETicket.result=" + _sellIBETicket__return);
//
//
//        }
//
//        System.exit(0);
//    }

}
