package com.viptrip.wetrip.wsclient;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "IBETicketImplDelegate", targetNamespace = "http://webservice.viptrip.com/")
public interface IBETicketImplDelegate {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SellIBETicket")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "SellIBETicket", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.SellIBETicket")
	@ResponseWrapper(localName = "SellIBETicketResponse", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.SellIBETicketResponse")
	public String sellIBETicket(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") int arg1);
	

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "splitPnrByName", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.SplitPnrByName")
    @ResponseWrapper(localName = "splitPnrByNameResponse", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.SplitPnrByNameResponse")
    public String splitPnrByName(@WebParam(name = "arg0", targetNamespace = "") String arg0,
            @WebParam(name = "arg1", targetNamespace = "") String arg1,
            @WebParam(name = "arg2", targetNamespace = "") boolean arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rrAndIssueIBETicke", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.RrAndIssueIBETicke")
    @ResponseWrapper(localName = "rrAndIssueIBETickeResponse", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.RrAndIssueIBETickeResponse")
    public String rrAndIssueIBETicke(@WebParam(name = "arg0", targetNamespace = "") String arg0,
            @WebParam(name = "arg1", targetNamespace = "") int arg1);



    /**
     * 
     * @param arg4
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changeDate", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.ChangeDate")
    @ResponseWrapper(localName = "changeDateResponse", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.ChangeDateResponse")
    public String changeDate(@WebParam(name = "arg0", targetNamespace = "") String arg0,
            @WebParam(name = "arg1", targetNamespace = "") String arg1,
            @WebParam(name = "arg2", targetNamespace = "") String arg2,
            @WebParam(name = "arg3", targetNamespace = "") String arg3,
            @WebParam(name = "arg4", targetNamespace = "") String arg4);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "changePnr", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.ChangePnr")
    @ResponseWrapper(localName = "changePnrResponse", targetNamespace = "http://webservice.viptrip.com/", className = "com.viptrip.wetrip.wsclient.ChangePnrResponse")
    public String changePnr(@WebParam(name = "arg0", targetNamespace = "") String arg0,
            @WebParam(name = "arg1", targetNamespace = "") List<String> arg1);

}
