package com.viptrip.wetrip.wsclient;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.viptrip.resource.Const;
import com.viptrip.util.PropertiesUtils;

import java.util.logging.Logger;

//import com.viptrip.base.util.PropertiesUtil;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-10-10T13:57:26.421+08:00
 * Generated source version: 2.7.6
 * 
 */
@WebServiceClient(name = "IBETicketImplService", targetNamespace = "http://webservice.viptrip.com/", wsdlLocation = "http://10.0.4.152:8089/new_ws/IBETicketImplPort?wsdl")
public class IBETicketImplService extends Service {

	private final static URL IBETICKETIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(IBETicketImplService.class
					.getName());

	static {
//		URL url = null;
//		
//		try {
//			URL baseUrl;
//			baseUrl = IBETicketImplService.class
//					.getResource(".");
//			url = new URL(baseUrl,
//					"http://10.0.4.152:8089/new_ws/IBETicketImplPort?wsdl");
//		} catch (MalformedURLException e) {
//			logger.warning("Failed to create URL for the wsdl Location: 'http://10.0.4.152:8089/new_ws/IBETicketImplPort?wsdl', retrying as a local file");
//			logger.warning(e.getMessage());
//		}
//		IBETICKETIMPLSERVICE_WSDL_LOCATION = url;
		
		
		URL url = null;
        StringBuffer partURL=new StringBuffer();
        try {
            partURL.append(PropertiesUtils.getProperty(Const.PRO_IBESERVER_IP,Const.FILE_IBESERVER));
            partURL.append(PropertiesUtils.getProperty(Const.PRO_IBESERVER_PORT,Const.FILE_IBESERVER));
        } catch (IOException e) {
            e.printStackTrace();
        }
        try {
            url = new URL("http://" + partURL + "/new_ws/IBETicketImplPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetIBETicketNoImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://" + partURL + 
                    "/new_ws/IBEPNRAddPATAImplPort?wsdl");
        }
        
        IBETICKETIMPLSERVICE_WSDL_LOCATION = url;
	}

	public IBETicketImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public IBETicketImplService() {
		super(IBETICKETIMPLSERVICE_WSDL_LOCATION, new QName(
				"http://webservice.viptrip.com/", "IBETicketImplService"));
	}

	/**
	 * 
	 * @return returns IBETicketImplDelegate
	 */
	@WebEndpoint(name = "IBETicketImplPort")
	public IBETicketImplDelegate getIBETicketImplPort() {
		return super.getPort(new QName("http://webservice.viptrip.com/",
				"IBETicketImplPort"), IBETicketImplDelegate.class);
	}

}
