package com.viptrip.wetrip.wsclient;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-10-11T17:29:07.662+08:00
 * Generated source version: 2.7.6
 * 
 */
public final class IBEvoidETicketImplDelegate_IBEvoidETicketImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.viptrip.com/", "IBEvoidETicketImplService");

    private IBEvoidETicketImplDelegate_IBEvoidETicketImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = IBEvoidETicketImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IBEvoidETicketImplService ss = new IBEvoidETicketImplService(wsdlURL, SERVICE_NAME);
        IBEvoidETicketImplDelegate port = ss.getIBEvoidETicketImplPort();  
        
        {
        //system.out.println("Invoking voidETicket...");
        java.lang.String _voidETicket_arg0 = "";
        java.lang.String _voidETicket_arg1 = "";
        java.lang.String _voidETicket_arg2 = "";
        java.lang.String _voidETicket_arg3 = "";
        java.lang.String _voidETicket__return = port.voidETicket(_voidETicket_arg0, _voidETicket_arg1, _voidETicket_arg2, _voidETicket_arg3);
        //system.out.println("voidETicket.result=" + _voidETicket__return);


        }

        System.exit(0);
    }

}
